[project]
name = "plc-platform-backend"
version = "0.1.0"
description = ""
authors = [{ name = "filippodaniotti", email = "febbrosto@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11,<3.12"

dependencies = [
    "fastapi[standard]>=0.115.6,<0.116.0",
    "uvicorn>=0.34.0,<0.35.0",
    "plctestbench",
    "pydantic-settings>=2.7.1,<3.0.0",
    "motor>=3.7.0,<4.0.0",
    "dramatiq[redis]>=1.18.0,<2.0.0",
]

[dependency-groups]
dev = ["debugpy>=1.8.11,<2.0.0"]

[tool.uv.sources]
plctestbench = { git = "https://github.com/CIMIL/plc-testbench", branch = "public" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["plc_platform_backend"]
