FROM --platform=linux/amd64 python:3.10-slim

WORKDIR /app/backend

COPY pyproject.toml poetry.lock ./

RUN pip install poetry==2.0.1 && poetry install --only main --no-root --no-directory

COPY . .

RUN poetry install --with dev

RUN chmod u+x .docker/docker-entrypoint.workers.sh

RUN chmod u+x .docker/docker-entrypoint.backend.dev.sh
